from building import *

cwd = GetCurrentDir()

# Board Include
CPPPATH = [
    cwd,
]


# Board Source
SRC_C = Glob(f"{cwd}/*c")


objs = DefineGroup("boot", SRC_C, depend= [""], CPPPATH = CPPPATH, LOCAL_CPPDEFINES=['__RT_IPC_SOURCE__'])

Return("objs")